order:
  items:
    - id: I1
      price:
        value: "100"
  fulfillments:
    - id: F1
      type: ONLINE
      customer:
        person:
          creds:
            - id: "00129812901"
              type: CARD_IDENTIFIER
  provider:
    id: P1
