order:
  provider:
    id: P1
  items:
    - id: I1
      price:
        value: "100"
  fulfillments:
    - id: F1
      type: ONLINE
      customer:
        contact:
          email: joe.adam@abc.org
          phone: "+91-9999999999"
        person:
          name: Joe Adam
          creds:
            - id: "00129812901"
              type: CARD_IDENTIFIER
  payments:
    - id: PA1
      collected_by: BAP
      type: PRE-ORDER
      status: NOT-PAID
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'
  billing:
    name: John Doe
    email: john.doe@example.com
    phone: "+91-9897867564"
