intent:
  category:
    descriptor:
      code: "GOLD_LOAN"
  payment:
    collected_by: "BPP"
    tags:
      - descriptor:
          code: "BUYER_FINDER_FEES"
        display: false
        list:
          - descriptor:
              code: "BUYER_FINDER_FEES_TYPE"
            value: "percent-annualized"
          - descriptor:
              code: "BUYER_FINDER_FEES_PERCENTAGE"
            value: "1"
      - descriptor:
          code: "SETTLEMENT_TERMS"
        display: false
        list:
          - descriptor:
              code: "DELAY_INTEREST"
            value: "2.5"
          - descriptor:
              code: "STATIC_TERMS"
            value: "https://bap.credit.becknprotocol.io/personal-banking/loans/gold-loan"
          - descriptor:
              code: "OFFLINE_CONTRACT"
            value: "true" 