order:
  provider:
    id: "PROVIDER_ID"
  items:
    - id: "ITEM_ID_GOLD_LOAN_1"
      location_ids:
        - "L2"
      xinput:
        form:
          id: "FO2"
        form_response:
          status: "SUCCESS"
          submission_id: "F02_SUBMISSION_ID"

