order:
  provider:
    id: P1

  items:
    - id: I2
      price:
        value: "0"

  fulfillments:
    - id: F1
      type: ONLINE
      customer:
        contact:
          email: joe.adam@abc.org
          phone: "+91-9999999999"
        person:
          name: Joe Adam
          creds:
            - id: "00129812901"
              type: CARD_IDENTIFIER

  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: BUYER_FINDER_FEES_PERCENTAGE
          value: "1"
        - descriptor:
            code: BUYER_FINDER_FEES_TYPE
          value: percent
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_BASIS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_WINDOW
          value: P30D

  billing:
    name: John Doe
    email: john.doe@example.com
    phone: "+91-9897867564"
