save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  payments: "$.message.order.payments[*]"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  created_at: "$.context.timestamp"
  updated_at: "$.context.timestamp"
  