catalog:
  descriptor:
    name: ABC Insurance Ltd
  providers:
    - id: P1
      descriptor:
        long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
        name: "ABC Insurance Ltd."
        short_desc: "ABC Insurance Ltd. India "
        images:
          - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
            size_type: xs
      categories:
        - id: C1
          descriptor:
            name: Micro Insurance
            code: MICRO_INSURANCE
        - id: C2
          parent_category_id: C1
          descriptor:
            name: Micro Hospicash Insurance
            code: MICRO_HOSPICASH_INSURANCE
      tags:
        - descriptor:
            code: MASTER_POLICY
          list:
            - descriptor:
                code: POLICY_ID
              value: e103b4a5-10f8-42c7-b888-dbf0e2edd696
      items:
        - id: I1
          category_ids: [C2]
          descriptor:
            name: Micro Hospicash Insurance
            short_desc: ABC Individual Insurance Class
          time:
            duration: P1Y
            label: TENURE

        - id: CHILD_ITEM_ID_I1
          parent_item_id: I1
          category_ids: [C2]
          descriptor:
            name: Micro Hospicash Insurance Plan
            short_desc: Individual Insurance Class
          price:
            currency: INR
            value: "900"
          time:
            duration: P1Y
            label: TENURE
          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - descriptor: { code: COVERAGE_AMOUNT }
                  value: "10000000"
                - descriptor: { code: DAILY_CASH_BENEFIT }
                  value: "1000"
                - descriptor: { code: MAX_HOSPITALIZATION_DAYS }
                  value: P10D
                - descriptor: { code: ICU_BENEFIT_PER_DAY }
                  value: "5000"
                - descriptor:
                    code: SURGICAL_BENEFIT
                    short_desc: Describes One-time payout for eligible surgery
                  value: "50000"
                - descriptor: { code: CONVALESCENCE_BENEFIT }
                  value: "500000"
                - descriptor: { code: MINIMUM_DAYS_FOR_CONVALESCENCE_BENEFIT }
                  value: P7D
                - descriptor: { code: INITIAL_WAITING_PERIOD }
                  value: P7D
                - descriptor: { code: DURATION_OF_COVER }
                  value: P7D
                - descriptor: { code: MINIMUM_AGE_LIMIT }
                  value: "18"
                - descriptor: { code: MAXIMUM_AGE_LIMIT }
                  value: "60"
                - descriptor:
                    code: BASE_PRICE
                    name: Base Price
                    short_desc: Base Price
                  value: "900"
                - descriptor:
                    code: CONVIENCE_FEE
                    name: Convience Fee
                    short_desc: Convience Fee
                  value: "50"
                - descriptor:
                    code: PROCESSING_FEE
                    name: Processing Fee
                    short_desc: Processing Fee
                  value: "10"
                - descriptor:
                    code: TAX
                    name: Tax
                    short_desc: Tax
                  value: "40"
                - descriptor:
                    code: OFFER_VALIDITY
                    name: Offer validity
                    short_desc: Describes the offer validity
                  value: P15D
            - descriptor:
                name: Inclusions
                code: INCLUSIONS
              list:
                - descriptor: { name: Hospitalization }
                - descriptor: { name: Surgery }
            - descriptor:
                name: Exclusions
                code: EXCLUSIONS
              list:
                - descriptor: { name: Physiotherapy }

        - id: CHILD_ITEM_ID_I2
          parent_item_id: I1
          category_ids: [C2]
          descriptor:
            name: Micro Hospicash Insurance Plus Plan
            short_desc: Single Transit Insurance
          price:
            currency: INR
            value: "1000"
          time:
            duration: P1Y
            label: TENURE
          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - descriptor: { code: COVERAGE_AMOUNT }
                  value: "10000000"
                - descriptor: { code: DAILY_CASH_BENEFIT }
                  value: "1000"
                - descriptor: { code: MAX_HOSPITALIZATION_DAYS }
                  value: P10D
                - descriptor: { code: ICU_BENEFIT_PER_DAY }
                  value: "5000"
                - descriptor:
                    code: SURGICAL_BENEFIT
                    short_desc: Describes One-time payout for eligible surgery
                  value: "50000"
                - descriptor: { code: CONVALESCENCE_BENEFIT }
                  value: "500000"
                - descriptor: { code: MINIMUM_DAYS_FOR_CONVALESCENCE_BENEFIT }
                  value: P7D
                - descriptor: { code: INITIAL_WAITING_PERIOD }
                  value: P7D
                - descriptor: { code: DURATION_OF_COVER }
                  value: P7D
                - descriptor: { code: MINIMUM_AGE_LIMIT }
                  value: "18"
                - descriptor: { code: MAXIMUM_AGE_LIMIT }
                  value: "60"
                - descriptor:
                    code: BASE_PRICE
                    name: Base Price
                    short_desc: Base Price
                  value: "1000"
                - descriptor:
                    code: CONVIENCE_FEE
                    name: Convience Fee
                    short_desc: Convience Fee
                  value: "50"
                - descriptor:
                    code: PROCESSING_FEE
                    name: Processing Fee
                    short_desc: Processing Fee
                  value: "10"
                - descriptor:
                    code: TAX
                    name: Tax
                    short_desc: Tax
                  value: "40"
                - descriptor:
                    code: OFFER_VALIDITY
                    name: Offer validity
                    short_desc: Describes the offer validity
                  value: P15D
            - descriptor:
                name: Inclusions
                code: INCLUSIONS
              list:
                - descriptor: { name: Hospitalization }
                - descriptor: { name: Medications }
                - descriptor: { name: Surgery }
            - descriptor:
                name: Exclusions
                code: EXCLUSIONS
              list:
                - descriptor: { name: Physiotherapy }

      payments:
        - collected_by: BPP
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  
       