catalog:
  descriptor:
    name: Transit Solutions
    images:
      - url: https://transitsolutions.in/logos/logo.icon

  providers:
    - id: P1
      categories:
        - id: C1
          descriptor:
            name: Wallet Management
            code: WALLET_MANAGEMENT
        - id: C2
          descriptor:
            name: Recharge
            code: RECHARGE
        - id: C3
          descriptor:
            name: Balance Check
            code: BALANCE_CHECK

      descriptor:
        name: Delhi Metro Rail Limited
        images:
          - url: https://delhimetrorail.com/logos/logo.ico

      items:
        - id: I1
          category_ids:
            - C1
            - C2
          descriptor:
            name: Metro Card Recharge
            code: RECHARGE
            images:
              - url: https://delhimetrorail.com/logos/logo.ico
          price:
            currency: INR
            value: "200"
            minimum_value: "50"
            maximum_value: "500"
          time:
            label: Validity
            duration: P1Y
          fulfillment_ids:
            - F1

        - id: I2
          category_ids:
            - C1
            - C3
          descriptor:
            name: Metro Balance Check
            code: BALANCE_CHECK
            images:
              - url: https://delhimetrorail.com/logos/logo.ico
          price:
            currency: INR
            value: "0"
            minimum_value: "0"
            maximum_value: "0"
          fulfillment_ids:
            - F1

      fulfillments:
        - id: F1
          type: ONLINE
          stops:
            - instructions:
                name: How to use?
                short_desc: short description about how to use?
                long_desc: description about how to use?

      payments:
        - collected_by: BAP

  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: BUYER_FINDER_FEES_PERCENTAGE
          value: "1"
        - descriptor:
            code: BUYER_FINDER_FEES_TYPE
          value: percent
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: MANDATORY_ARBITRATION
          value: "true"
        - descriptor:
            code: COURT_JURISDICTION
          value: New Delhi
        - descriptor:
            code: DELAY_INTEREST
          value: 2.5 %
