order:
  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
      category_ids:
        - "C2"
      descriptor:
        name: "Micro Transit Insurance Plan"
        short_desc: "Individual Insurance Class"
      price:
        currency: "INR"
        value: "900"
      tags:
        - descriptor:
            name: "General Information"
            code: "GENERAL_INFO"
          list:
            - descriptor:
                code: "COVERAGE_AMOUNT"
              value: "10000000"
        - descriptor:
            name: "Inclusions"
            code: "INCLUSIONS"
          list:
            - descriptor:
                name: "Transit Coverage"
            - descriptor:
                name: "Multi-Mode Transport Protection"
            - descriptor:
                name: "Natural Calamities"
        - descriptor:
            name: "Exclusions"
            code: "EXCLUSIONS"
          list:
            - descriptor:
                name: "Ordinary Wear and Tear"
            - descriptor:
                name: "Delays"
                short_desc: "Describes financial loss or damage caused due to transit delays is not covered"
      time:
        duration: "P1Y"
        label: "TENURE"

  provider:
    descriptor:
      long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
      name: "ABC Insurance Ltd."
      short_desc: "ABC Insurance Ltd. India "
      images:
        - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
          size_type: "xs"
    id: "P1"
    tags:
      - descriptor:
          code: "MASTER_POLICY"
        list:
          - descriptor:
              code: "POLICY_ID"
            value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"

  quote:
    id: "OFFER_ID/PROPOSAL_ID"
    breakup:
      - price:
          value: "900"
          currency: "INR"
        title: "BASE_PRICE"
      - price:
          value: "50"
          currency: "INR"
        title: "CONVIENCE_FEE"
      - price:
          value: "40"
          currency: "INR"
        title: "TAX"
      - price:
          value: "10"
          currency: "INR"
        title: "PROCESSING_FEE"
    price:
      currency: "INR"
      value: "1000"

  fulfillments:
    - id: "F1"
      type: "POLICY"
      tags:
        - descriptor:
            code: "NOMINEE_DETAILS"
            name: "Nominee Details"
          display: true
          list:
            - descriptor:
                code: "NOMINEE_NAME"
                short_desc: "Describes the nominee name in the format as 'Salutation | First Name | Middle Name | Last Name' represents a full name structure, where the values are separated by a pipe (|) symbol"
              value: "John"
