order:
  provider:
    id: "PROVIDER_ID"
    descriptor:
      images:
        - url: "https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png"
          size_type: "sm"
      name: "ICICI Bank"
      short_desc: "ICICI Bank Ltd"
      long_desc: "ICICI Bank Ltd, India."
  items:
    - id: "ITEM_ID_GOLD_LOAN_1"
      descriptor:
        code: "LOAN"
        name: "Gold Loan without AA"
      price:
        currency: "INR"
        value: "441800"
      location_ids:
        - "L2"
      xinput:
        head:
          descriptor:
            name: "Set Loan Amount"
          index:
            min: 0
            cur: 0
            max: 1
          headings:
            - "SET_LOAN_AMOUNT"
            - "JOURNEY_OFFLINE"
        form:
          id: "FO2"
          mime_type: "text/html"
          url: "https://bpp.credit.becknprotocol.org/loans-details/xinput?formid=FO2"
          resubmit: false
          multiple_sumbissions: false
        required: true
  quote:
    id: "LOAN_LEAD_ID_OR_SIMILAR"
    price:
      currency: "INR"
      value: "442300"
    breakup:
      - title: "PRINCIPAL"
        price:
          value: "400000"
          currency: "INR"
      - title: "INTEREST"
        price:
          value: "40000"
          currency: "INR"
      - title: "PROCESSING_FEE"
        price:
          value: "1800"
          currency: "INR"
      - title: "OTHER_UPFRONT_CHARGES"
        price:
          value: "0"
          currency: "INR"
      - title: "INSURANCE_CHARGES"
        price:
          value: "500"
          currency: "INR"
      - title: "NET_DISBURSED_AMOUNT"
        price:
          value: "397700"
          currency: "INR"
      - title: "OTHER_CHARGES"
        price:
          value: "0"
          currency: "INR"
    ttl: "PT15D"
