save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  collected_by: "$.message.intent.payment.collected_by" 
  descriptor_code: "$.message.intent.category.descriptor.code" 
  tags: "$.message.intent.provider[*].tags[*]" 
  policy_id: "$.message.intent.provider.tags[*].list[*].value" 
  city_code: "$.context.location.city.code"
