order:
  fulfillments:
    - id: "F1"
      type: "POLICY"
      tags:
        - descriptor:
            code: "NOMINEE_DETAILS"
            name: "Nominee Details"
          display: false
          list:
            - descriptor:
                code: "NOMINEE_NAME"
              value: "Mr. | Steve | Wick | Adams"
  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
  provider:
    id: "P1"
  payments:
    - collected_by: "BPP"
      status: "NOT-PAID"
      type: "PRE-ORDER"
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'
