intent:
  category:
    descriptor:
      code: "MICRO_HOSPICASH_INSURANCE"
  fulfillment:
    agent:
      person:
        id: "0120TRVK"
  payment:
    collected_by: "BPP"
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  