order:
  provider:
    id: "PROVIDER_ID"
  items:
    - id: "ITEM_ID_GOLD_LOAN_1"
  payments:
    - id: "PAYMENT_ID_GOLD_LOAN"
      collected_by: "BPP"
      type: "ON_ORDER"
      status: "NOT-PAID"
      params:
        bank_code: "XXXXXXXX"
        bank_account_number: "xxxxxxxxxxxxxx"
        virtual_payment_address: "9988199772@okicic"
      tags:
        - descriptor:
            code: "BUYER_FINDER_FEES"
          display: false
          list:
            - descriptor:
                code: "BUYER_FINDER_FEES_TYPE"
              value: "percent-annualized"
            - descriptor:
                code: "BUYER_FINDER_FEES_PERCENTAGE"
              value: "1"
        - descriptor:
            code: "SETTLEMENT_TERMS"
          display: false
          list:
            - descriptor:
                code: "SETTLEMENT_AMOUNT"
              value: "1159"
            - descriptor:
                code: "SETTLEMENT_TYPE"
              value: "neft"
            - descriptor:
                code: "DELAY_INTEREST"
              value: "5"
            - descriptor:
                code: "STATIC_TERMS"
              value: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
            - descriptor:
                code: "OFFLINE_CONTRACT"
              value: "true" 