catalog:
  descriptor:
    name: "ABC Insurance Ltd"
  providers:
    - categories:
        - descriptor:
            name: "Micro Insurance"
            code: "MICRO_INSURANCE"
          id: "C1"
        - descriptor:
            name: "Micro Transit Insurance"
            code: "MICRO_TRANSIT_INSURANCE"
          parent_category_id: "C1"
          id: "C2"
      descriptor:
        long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
        name: "ABC Insurance Ltd."
        short_desc: "ABC Insurance Ltd. India "
        images:
          - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
            size_type: "xs"
      id: "P1"
      tags:
        - descriptor:
            code: "MASTER_POLICY"
          list:
            - descriptor:
                code: "POLICY_ID"
              value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"
      items:
        - id: "I1"
          category_ids:
            - "C2"
          descriptor:
            name: "Micro Transit Insurance"
            short_desc: "ABC Individual Insurance Class"
          time:
            duration: "P1Y"
            label: "TENURE"
          tags:
            - descriptor:
                code: "BAP_INPUTS"
              list:
                - descriptor:
                    code: "BUYER_NAME"
                  value: "-"
                - descriptor:
                    code: "BUYER_PHONE_NUMBER"
                  value: "-"
                - descriptor:
                    code: "BUYER_PAN_NUMBER"
                  value: "-"
                - descriptor:
                    code: "DERIVED_DATA"
                    short_desc: "Describes the derived data in the form of a URL pointing to a JSON file."
                  value: "-"
                - descriptor:
                    code: "PRODUCT_CATEGORY"
                  value: "-"
                - descriptor:
                    code: "ORDER_ID"
                  value: "-"
                - descriptor:
                    code: "ORDER_VALUE"
                  value: "-"
                - descriptor:
                    code: "ORDER_TYPE"
                  value: "-"
                - descriptor:
                    code: "ORDER_WEIGHT"
                  value: "-"
                - descriptor:
                    code: "START_ADDRESS"
                    short_desc: "Describes the start address, including the pincode location."
                  value: "-"
                - descriptor:
                    code: "END_ADDRESS"
                    short_desc: "Describes the start address, including the pincode location."
                  value: "-"
                - descriptor:
                    code: "PAYMENT_MODE"
                  value: "-"
                - descriptor:
                    code: "TRANSIT_START_DATE"
                  value: "-"
                - descriptor:
                    code: "TRANSIT_END_DATE"
                  value: "-"
                - descriptor:
                    code: "PACKAGING_TYPE"
                  value: "-"
                - descriptor:
                    code: "PACKAGING_VIDEO"
                    short_desc: "Describes the packaging video tag value, including the URL, format type, and validity period."
                  value: "-"
                - descriptor:
                    code: "SEALING_TYPE"
                  value: "-"
                - descriptor:
                    code: "WATERPROOFING"
                  value: "-"
                - descriptor:
                    code: "MODE_OF_TRANSPORT"
                  value: "-"
                - descriptor:
                    code: "LOGISTICS_COST"
                  value: "-"
                - descriptor:
                    code: "ORDERS_ONTIME_PCT"
                    short_desc: "Descriebs percentage of orders that were shipped on or before the scheduled time."
                  value: "-"
                - descriptor:
                    code: "LOGISTICS_PARTNER_GSTIN"
                  value: "-"
                - descriptor:
                    code: "DELIVERY_EXECUTIVE_NAME"
                  value: "-"
                - descriptor:
                    code: "DELIVERY_EXECUTIVE_PHONE_NO"
                  value: "-"
                - descriptor:
                    code: "DELIVERY_EXECUTIVE_UNIQUE_ID"
                  value: "-"
                - descriptor:
                    code: "DELIVERY_EXECUTIVE_VEHICLE_NO"
                  value: "-"
      payments:
        - collected_by: "BPP"
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  
       