catalog:
  descriptor:
    name: "ABC Insurance Ltd"
  providers:
    - id: "P1"
      categories:
        - id: "C1"
          descriptor:
            name: "Micro Insurance"
            code: "MICRO_INSURANCE"
        - id: "C2"
          parent_category_id: "C1"
          descriptor:
            name: "Micro Hospicash Insurance"
            code: "MICRO_HOSPICASH_INSURANCE"
      descriptor:
        name: "ABC Insurance Ltd."
        short_desc: "ABC Insurance Ltd. India "
        long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
        images:
          - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
            size_type: "xs"
      tags:
        - descriptor:
            code: "MASTER_POLICY"
          list:
            - descriptor:
                code: "POLICY_ID"
              value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"
      items:
        - id: "I1"
          category_ids:
            - "C2"
          descriptor:
            name: "Micro Hospicash Insurance"
            short_desc: "ABC Individual Insurance Class"
          time:
            label: "TENURE"
            duration: "P1Y"
          tags:
            - descriptor:
                code: "BAP_INPUTS"
              list:
                - descriptor:
                    code: "BUYER_NAME"
                    short_desc: "Describes the format as  'Salutation | First Name | Middle Name | Last Name' represents a full name structure, where the values are separated by a pipe (|) symbol"
                  value: "A"
                - descriptor:
                    code: "BUYER_PHONE_NUMBER"
                    short_desc: "Describes the format as: the first two characters represent the country code, followed by a 10-digit mobile number, separated by a hyphen (-)."
                  value: "B"
                - descriptor:
                    code: "BUYER_PAN_NUMBER"
                    short_desc: "Describes the PAN number in alphanumeric format"
                  value: "C"
                - descriptor:
                    code: "BUYER_DOB"
                    short_desc: "Describes the format as: DD/MM/YYYY, separated by a forward slash ( / )."
                  value: "D"
                - descriptor:
                    code: "BUYER_GENDER"
                    short_desc: "Describes the values as male, female & transgender."
                  value: "E"
                - descriptor:
                    code: "SUM_INSURED"
                    short_desc: "Describes the format as: a numerical value without separators"
                  value: "F"
                - descriptor:
                    code: "BUYER_EMAIL"
                  value: "G"
                - descriptor:
                    code: "TENURE"
                    short_desc: "Describes the tenure in ISO 8601 duration format like P6M = 6 months &  P1Y = 1 year etc."
                  value: "H"
      payments:
        - collected_by: "BPP"
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  
         