order:
  provider:
    id: P1
    descriptor:
      name: Delhi Metro Rail Limited
      images:
        - url: https://delhimetrorail.com/logos/logo.icon

  items:
    - id: I1
      category_ids:
        - C1
      descriptor:
        name: Metro Card Recharge
        code: RECHARGE
        images:
          - url: https://delhimetrorail.com/logos/logo.ico
      price:
        currency: INR
        value: "100"
      time:
        label: Validity
        duration: P1Y
      fulfillment_ids:
        - F1

  fulfillments:
    - id: F1
      type: ONLINE
      customer:
        person:
          creds:
            - id: "00129812901"
              type: CARD_IDENTIFIER
      stops:
        - instructions:
            name: How to use?
            short_desc: short description about how to use?
            long_desc: Description about how to use?

  quote:
    id: Q1
    price:
      currency: INR
      value: "100"
    breakup:
      - title: BASE_FARE
        item:
          id: I1
          price:
            currency: INR
            value: "100"
      - title: CONVENIENCE_FEE
        price:
          currency: INR
          value: "10"
      - title: TAX
        price:
          currency: INR
          value: "0"
      - title: OFFER
        price:
          currency: INR
          value: "-10"
