order:
  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
      category_ids:
        - "C2"
      descriptor:
        name: "Micro Hospicash Insurance Plan"
        short_desc: "Individual Insurance Class"
      price:
        currency: "INR"
        value: "900"
      fulfillment_ids:
        - "F1"
      payment_ids:
        - "PA1"
      tags:
        - descriptor:
            name: "General Information"
            code: "GENERAL_INFO"
          list:
            - descriptor:
                code: "COVERAGE_AMOUNT"
              value: "10000000"
            - descriptor:
                code: "DAILY_CASH_BENEFIT"
              value: "1000"
            - descriptor:
                code: "MAX_HOSPITALIZATION_DAYS"
              value: "P10D"
            - descriptor:
                code: "ICU_BENEFIT_PER_DAY"
              value: "5000"
            - descriptor:
                code: "SURGICAL_BENEFIT"
                short_desc: "Describes One-time payout for eligible surgery"
              value: "50000"
            - descriptor:
                code: "CONVALESCENCE_BENEFIT"
              value: "500000"
            - descriptor:
                code: "MINIMUM_DAYS_FOR_CONVALESCENCE_BENEFIT"
              value: "P7D"
            - descriptor:
                code: "INITIAL_WAITING_PERIOD"
              value: "P7D"
            - descriptor:
                code: "DURATION_OF_COVER"
              value: "P7D"
            - descriptor:
                code: "MINIMUM_AGE_LIMIT"
              value: "18"
            - descriptor:
                code: "MAXIMUM_AGE_LIMIT"
              value: "60"
        - descriptor:
            name: "Inclusions"
            code: "INCLUSIONS"
          list:
            - descriptor:
                name: "Hospitalization"
            - descriptor:
                name: "Surgery"
        - descriptor:
            name: "Exclusions"
            code: "EXCLUSIONS"
          list:
            - descriptor:
                name: "Physiotherapy"
      time:
        duration: "P1Y"
        label: "TENURE"

  provider:
    descriptor:
      long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
      name: "ABC Insurance Ltd."
      short_desc: "ABC Insurance Ltd. India "
      images:
        - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
          size_type: "xs"
    id: "P1"
    tags:
      - descriptor:
          code: "MASTER_POLICY"
        list:
          - descriptor:
              code: "POLICY_ID"
            value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"

  quote:
    id: "OFFER_ID/PROPOSAL_ID"
    breakup:
      - price:
          value: "900"
          currency: "INR"
        title: "BASE_PRICE"
      - price:
          value: "50"
          currency: "INR"
        title: "CONVIENCE_FEE"
      - price:
          value: "40"
          currency: "INR"
        title: "TAX"
      - price:
          value: "10"
          currency: "INR"
        title: "PROCESSING_FEE"
    price:
      currency: "INR"
      value: "1000"

  cancellation_terms:
    - external_ref:
        mimetype: "text/html,"
        url: "https://fis.test.bpp.io/cancellation-terms"

  payments:
    - id: "PA1"
      collected_by: "BPP"
      url: "https://fis.test.bpp.io/pg-gateway/payment?amount=1000&txn_id=c04a04ee-d892-400f-bbe6-479a43b4448a"
      status: "NOT-PAID"
      type: "PRE-ORDER"

  fulfillments:
    - customer:
        person:
          name: "Mr. | Joe | Wick | Adams"
          dob: "2001-12-17"
          gender: "M"
        contact:
          phone: "+91-9988776655"
          email: "john.doe@example.com"
      id: "F1"
      type: "POLICY"
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  
       