catalog:
  descriptor:
    name: "ABC Insurance Ltd"
  providers:
    - categories:
        - descriptor:
            name: "Micro Insurance"
            code: "MICRO_INSURANCE"
          id: "C1"
        - descriptor:
            name: "Micro Transit Insurance"
            code: "MICRO_TRANSIT_INSURANCE"
          parent_category_id: "C1"
          id: "C2"
      descriptor:
        long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
        name: "ABC Insurance Ltd."
        short_desc: "ABC Insurance Ltd. India "
        images:
          - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
            size_type: "xs"
      id: "P1"
      tags:
        - descriptor:
            code: "MASTER_POLICY"
          list:
            - descriptor:
                code: "POLICY_ID"
              value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"
      items:
        - id: "I1"
          category_ids: 
            - "C2"
          descriptor:
            name: "Micro Transit Insurance"
            short_desc: "ABC Individual Insurance Class"
          time:
            duration: "P1Y"
            label: "TENURE"

        - id: "CHILD_ITEM_ID_I1"
          parent_item_id: "I1"
          category_ids: 
            - "C2"
          descriptor:
            name: "Micro Transit Insurance Plan"
            short_desc: "Individual Insurance Class"
          price:
            currency: "INR"
            value: "900"
          tags:
            - descriptor:
                name: "General Information"
                code: "GENERAL_INFO"
              list:
                - descriptor:
                    code: "COVERAGE_AMOUNT"
                  value: "10000000"
                - descriptor:
                    code: "BASE_PRICE"
                    name: "Base Price"
                    short_desc: "Base Price"
                  value: "900"
                - descriptor:
                    code: "CONVIENCE_FEE"
                    name: "Convience Fee"
                    short_desc: "Convience Fee"
                  value: "50"
                - descriptor:
                    code: "PROCESSING_FEE"
                    name: "Processing Fee"
                    short_desc: "Processing Fee"
                  value: "10"
                - descriptor:
                    code: "TAX"
                    name: "Tax"
                    short_desc: "Tax"
                  value: "40"
                - descriptor:
                    code: "OFFER_VALIDITY"
                    name: "Offer validity"
                    short_desc: "Describes the offer validity"
                  value: "P15D"
            - descriptor:
                name: "Inclusions"
                code: "INCLUSIONS"
              list:
                - descriptor:
                    name: "Transit Coverage"
                - descriptor:
                    name: "Multi-Mode Transport Protection"
                - descriptor:
                    name: "Natural Calamities"
            - descriptor:
                name: "Exclusions"
                code: "EXCLUSIONS"
              list:
                - descriptor:
                    name: "Ordinary Wear and Tear"
                - descriptor:
                    name: "Delays"
                    short_desc: "Describes financial loss or damage caused due to transit delays is not covered"
          time:
            duration: "P1Y"
            label: "TENURE"

        - id: "CHILD_ITEM_ID_I2"
          parent_item_id: "I1"
          category_ids: 
            - "C2"
          descriptor:
            name: "Micro Transit Insurance Plus Plan"
            short_desc: "Single Transit Insurance"
          price:
            currency: "INR"
            value: "1000"
          tags:
            - descriptor:
                name: "General Information"
                code: "GENERAL_INFO"
              list:
                - descriptor:
                    code: "COVERAGE_AMOUNT"
                  value: "10000000"
                - descriptor:
                    code: "CO_PAYMENT"
                  value: "Yes"
                - descriptor:
                    code: "CLAIM_SETTLEMENT_RATIO"
                  value: "20.3"
                - descriptor:
                    code: "BASE_PRICE"
                    name: "Base Price"
                    short_desc: "Base Price"
                  value: "1000"
                - descriptor:
                    code: "CONVIENCE_FEE"
                    name: "Convience Fee"
                    short_desc: "Convience Fee"
                  value: "50"
                - descriptor:
                    code: "PROCESSING_FEE"
                    name: "Processing Fee"
                    short_desc: "Processing Fee"
                  value: "10"
                - descriptor:
                    code: "TAX"
                    name: "Tax"
                    short_desc: "Tax"
                  value: "40"
                - descriptor:
                    code: "OFFER_VALIDITY"
                    name: "Offer validity"
                    short_desc: "Describes the offer validity"
                  value: "P15D"
            - descriptor:
                name: "Inclusions"
                code: "INCLUSIONS"
              list:
                - descriptor:
                    name: "Transit Coverage"
                - descriptor:
                    name: "Multi-Mode Transport Protection"
                - descriptor:
                    name: "Accidental Damages"
            - descriptor:
                name: "Exclusions"
                code: "EXCLUSIONS"
              list:
                - descriptor:
                    name: "Inherent Vice"
                    short_desc: "Describes losses due to the natural characteristics or deterioration of goods are not covered"
          time:
            duration: "P1Y"
            label: "TENURE"

      payments:
        - collected_by: "BPP"
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  
       