save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  items: "$.message.catalog.providers[*].items[*]"
  on_search_tags: "$.message.catalog.providers[*].tags[*]"
  on_search_provider: "$.message.catalog.providers[*]"
  item: "$.message.catalog.providers[].items[0]"
  # city_code: "$context.location.city.code"
  # provider_id: "$.message.catalog.providers[0].id"
  fulfillments: "$.message.catalog.providers[0].fulfillments[*]"
