name: Deploy Mock Service

on:
  workflow_dispatch:
  push:
    branches:
      - "draft/*"
      - "release/*"

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    environment: |
      ${{
        (startsWith(github.ref_name, 'release') && format('release-{0}', github.ref_name)) ||
        (startsWith(github.ref_name, 'draft') && format('draft-{0}', github.ref_name)) ||
        (startsWith(github.ref_name, 'release') && 'release') ||
        (startsWith(github.ref_name, 'draft') && 'draft') ||
        'default'
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect build type
        run: |
          if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
            echo "BUILD_TYPE=draft" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
            echo "BUILD_TYPE=release" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=default" >> $GITHUB_ENV
          fi

      - name: Print environment variables (sanitized)
        run: |
          echo "---- Effective environment variables ----"
          env | grep -v -i "PASSWORD\|KEY\|SECRET" | sort

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}
          docker build -t $IMAGE_NAME:${{ github.sha }} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run container locally
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}
          docker run -d --rm --name mock-test \
            -p ${{ vars.PORT }}:${{ vars.PORT }} \
            $IMAGE_NAME:${{ github.sha }}
          sleep 5

      - name: Healthcheck
        run: |
          HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
          echo "Checking $HEALTHCHECK_URL ..."
          for i in {1..10}; do
            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
              echo "✅ Container is healthy"
              exit 0
            fi
            echo "Waiting... ($i)"
            sleep 2
          done
          echo "❌ Healthcheck failed!"
          docker logs mock-test
          exit 1

      - name: Stop test container
        if: always()
        run: docker stop mock-test || true

      - name: Tag & Push Images
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:stable
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:stable

  deploy:
    needs: build-and-verify
    runs-on: ubuntu-latest
    environment: |
      ${{
        (startsWith(github.ref_name, 'release') && format('release-{0}', github.ref_name)) ||
        (startsWith(github.ref_name, 'draft') && format('draft-{0}', github.ref_name)) ||
        (startsWith(github.ref_name, 'release') && 'release') ||
        (startsWith(github.ref_name, 'draft') && 'draft') ||
        'default'
      }}
    steps:
      - name: Detect build type
        run: |
          if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
            echo "BUILD_TYPE=draft" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
            echo "BUILD_TYPE=release" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=default" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_DIR="/opt/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}"
            mkdir -p $REPO_DIR

            echo "Writing .env file..."
            cat > $REPO_DIR/.env <<EOF
            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            PORT=${{ vars.PORT }}
            API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
            DOMAIN=${{ vars.DOMAIN }}
            CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
            API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
            FORM_SERVICE=${{ vars.FORM_SERVICE }}
            NODE_ENV=${{ vars.NODE_ENV }}
            LOKI_HOST=${{ vars.LOKI_HOST }}
            EOF

            IMAGE_NAME=ghcr.io/${{ github.repository }}/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}

            echo "Pulling latest image..."
            docker pull $IMAGE_NAME:stable || docker pull $IMAGE_NAME:${{ github.sha }}

            echo "Restarting container..."
            docker stop automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true
            docker rm automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true

            docker run -d --name automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} \
              --env-file $REPO_DIR/.env \
              -p ${{ vars.PORT }}:${{ vars.PORT }} \
              $IMAGE_NAME:stable
