order:
  fulfillments:
    - customer:
        person:
          name: "Mr. | Joe | Wick | Adams"
        contact:
          phone: "+91-9988776655"
      id: "F1"
      type: "POLICY"
  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
  provider:
    id: "P1"
  payments:
    - id: "PA1"
      collected_by: "BPP"
      status: "NOT-PAID"
      type: "PRE-ORDER"
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'
